### PR TITLE
UICAL-229 test WeekdayPicker

### PR DESCRIPTION
**Pull request by zburke**
Test `src/components/fields/WeekdayPicker.tsx`

Refs [UICAL-229](https://issues.folio.org/browse/UICAL-229)

### CODE REVIEW

**Comment by ncovercash** [comment]
Looks good; tiny nitpick: please replace `'SUNDAY'` with `Weekdays.Sunday` (imported with `import * as Weekdays from '../../test/data/Weekdays'`) to avoid having the hardcoded string

**Review by ncovercash — CHANGES_REQUESTED** [review]
Looks good; tiny nitpick: please replace `'SUNDAY'` with `Weekdays.Sunday` (imported with `import * as Weekdays from '../../test/data/Weekdays'`) to avoid having the hardcoded string

**Comment by zburke** [comment]
> Looks good; tiny nitpick: please replace `'SUNDAY'` with `Weekdays.Sunday` (imported with `import * as Weekdays from '../../test/data/Weekdays'`) to avoid having the hardcoded string

Ah, could not figure out the right syntax and tried so many other things. Good call. Thank you!

**Comment by ncovercash** [comment]
Gotcha -- intellisense does not seem to appreciate `import * as ...` suggestions.  There's also a few in there for Dates, times, and some other fun stuff (and if you find others that might be helpful, feel free to add)

**Review by ncovercash — APPROVED** [review]

**Pull request merged**
