### PR TITLE
UICAL-250: create Cypress test - "Checking the view of calendar on 'All Calendars' tab"

### PR DESCRIPTION
**Pull request by GoZaddy**
# [Jira](https://issues.folio.org/browse/UICAL-250)

Completed task in UICAL-250

## Screenshots
Screen Shot 2022-11-05 at 1 34 51 PM

### CODE REVIEW

**Review by ncovercash — CHANGES_REQUESTED** [review]
All this looks great!  Since you're testing the info pane (the sidebar after clicking on the row), would it be possible to also test a calendar with all the fields fleshed out displays properly (this can be a separate ticket/PR if you want)

Also, we already have some sample calendars for the other tests in src/test/data/Calendars.ts - it'd be cool if those could be reused (or if anything more could be added there, to keep it together).  Also, I believe the service points 1 and 2 there have the same UUIDs as are used in snapshot, if you want to test against those

**Comment by GoZaddy** [comment]
> All this looks great! Since you're testing the info pane (the sidebar after clicking on the row), would it be possible to also test a calendar with all the fields fleshed out displays properly (this can be a separate ticket/PR if you want)
> 
> Also, we already have some sample calendars for the other tests in src/test/data/Calendars.ts - it'd be cool if those could be reused (or if anything more could be added there, to keep it together). Also, I believe the service points 1 and 2 there have the same UUIDs as are used in snapshot, if you want to test against those

@ncovercash Yeah, I'll open a new PR for that. Just to confirm, I should switch to using the data in src/test/data/Calendars.ts to create test calendars?

**Comment by ncovercash** [comment]
@GoZaddy either switch to it or add your own test data in there - just trying to keep it in one place

**Comment by GoZaddy** [comment]
Got it!

**Review by ncovercash — APPROVED** [review]
LGTM!  Feel free to squash and merge whenever you're ready

**Review by ncovercash — CHANGES_REQUESTED** [review]
Wait, just saw the failing CI build.  I think that's my fault, one sec

**Review by ncovercash — APPROVED** [review]
Added a commit to fix the bad test

**Pull request merged**
