### PR TITLE
UICAL-224 test for OpenClosedSelect

### PR DESCRIPTION
**Pull request by zburke**
Test `src/components/fields/OpenClosedSelect`. The `react-intl` mock is included locally in order to avoid breaking tests that have already been written that rely on it _not_ being mocked. Is it better to have a test that mocks a bunch of things but simple calls `render`, or a test with no mocks that calls a heavier render-helper? Six of one, half dozen of another. 

Footnotes:
* include jest globals in `.eslintrc` so lint doesn't barf on tests
* correct `@folio/stripes-*` versions in `package.json` to avoid CI release versions.

Refs [UICAL-224](https://issues.folio.org/browse/UICAL-224)

### CODE REVIEW

**Comment by ncovercash** [comment]
This looks good, thanks!  Good catch on the eslint with Jest - I wasn't aware of that option.

For the react-intl mock, what do you think the best approach would be?  I really want to have tests that check for multiple timezones/locales, so I had leaned towards including real `react-intl`, however, if you think it'd be better to implement a mock that does that instead, we can work towards that.  I also would prefer the `intl` be as accurate of a `react-intl` reflection as possible, just in case the `react-intl` behavior changes -- although I doubt this would happen, I wouldn't want the tests to miss a change that would break our usage because the usage is mocked over.

Currently, there's a simple `getIntl` helper that renders a `IntlContext` and captures the derived `intl` -- if we wanted to continue using real `intl`s, we could maybe put them all into a memoized test at least, to make the consuming tests less heavy.

I'm not too familiar with best practices in Jest, so I'll defer to you in that regard -- let me know what you think might be best and we can go from there.

**Comment by ncovercash** [comment]
@zburke if you want to move this conversation over to Slack, I can go ahead and merge this and we can continue there, too

**Review by ncovercash — APPROVED** [review]

**Comment by zburke** [comment]
Ideally, I'd figure out how to make this test use the `getIntl` helper you have; there's zero reason for this test to be special. The TS syntax is just so heavy I couldn't figure it out after staring at `<Thing <OtherThing<OtherOtherThing>>>>>>>>>`  for a while. Sorry. I'll grep for `getIntl` and see if there's an example I can follow 🤝 .

**Comment by ncovercash** [comment]
Lol, I totally get it -- generic generics get a bit insane.

Here's a nice snippet for ya:

```ts

let intlEn: IntlShape;
let intlFr: IntlShape;

beforeAll(() => {
  intlEn = getIntl('en-US', 'EST');
  intlFr = getIntl('fr-FR', 'CET');
});

```

Just throw this at the beginning of your test and it'll fill those variables with the needed `intl`s for that locale/timezone!

**Comment by ncovercash** [comment]
As soon as you get that, let me know – I've got a commit for a memoized getIntl but I don't want you to have to deal with any merge conflicts!

**Comment by ncovercash** [comment]
> Lol, I totally get it -- generic generics get a bit insane.
> 
> Here's a nice snippet for ya:
> 
> ```ts
> let intlEn: IntlShape;
> let intlFr: IntlShape;
> 
> beforeAll(() => {
>   intlEn = getIntl('en-US', 'EST');
>   intlFr = getIntl('fr-FR', 'CET');
> });
> ```
> 
> Just throw this at the beginning of your test and it'll fill those variables with the needed `intl`s for that locale/timezone!

oops, just looked a little closer.  not sure the getIntl helper there would work, but we could also make a wrapper that'll wrap a component in `<IntlProvider>` or something

**Comment by zburke** [comment]
Aha! Found `src/test/util/withIntlConfiguration`. That work is already done 🚀

**Comment by ncovercash** [comment]
Lol, forgot that was there!

**Review by ncovercash — APPROVED** [review]

**Comment by ncovercash** [comment]
Thank you so much!

**Pull request merged**
